name: "Dependency Review"
on: [pull_request]

# NOTE: THIS CONFIGURATION REDUCES THE PERMISSIONS OF THIS GITHUB ACTION.
# --------------------------------------------------------------------------------------------------------------------
# See:
# https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
# --------------------------------------------------------------------------------------------------------------------
# Explicitly adds `pull-requests: write` so that this action can update a PR.
# Retains `contents: read` for repo analysis.
# All other permissions are withheld.

permissions:
  contents: read
  pull-requests: write

# This workflow runs `actions/dependency-review-action` from the `reusable-github-workflows` repo.
# This resuable workflow approach is intended to speed up the process of deploying license updates
jobs:
  dependency_review:
    uses: the-control-group/reusable-github-workflows/.github/workflows/dependency_review.yml@ga
